2023-03-06 20:38:46.813814 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2023-03-06 20:39:51.068263 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2023-03-06 20:44:13.264834 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2023-03-06 20:44:40.190533 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2023-03-06 20:45:24.731064 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2023-05-24 07:30:29.894132 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2023-05-24 07:30:45.213788 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2023-05-24 07:31:40.388194 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2023-05-24 07:32:19.171131 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2024-01-17 17:32:34.273470 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---'..
2024-01-17 17:35:58.269042 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---'..
2024-01-17 17:36:24.614970 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---'..
2024-01-17 17:36:41.735973 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---'..
2024-01-17 17:37:18.943312 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---'..
2024-01-17 17:38:50.953855 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---'..
2024-01-17 17:39:01.077196 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---'..
2024-01-17 17:39:13.400780 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---'..
2024-01-17 17:39:19.703817 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"---'..
2024-01-18 14:54:30.492808 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2024-01-18 14:54:53.137668 (ERROR)    | Error: Could not connect to the database: 'connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused---	Is the server running on that host and accepting TCP/IP connections?---'..
2024-04-17 22:18:42.866270 (ERROR)    | Error: Could not connect to the database: 'connection to server at "192.168.168.20", port 5432 failed: Operation timed out---	Is the server running on that host and accepting TCP/IP connections?---'..
2024-04-17 22:20:24.101241 (ERROR)    | Error: Could not connect to the database: 'connection to server at "192.168.168.20", port 5432 failed: Operation timed out---	Is the server running on that host and accepting TCP/IP connections?---'..
2024-05-28 14:42:22,598 - Could not read config file. Exiting...
2024-05-28 14:45:06,297 - Could not read config file. Exiting...
2024-05-28 14:45:46,885 - Could not read config file. Exiting...
2024-05-28 14:45:54,191 - Could not read config file. Exiting...
2024-05-28 14:46:12,826 - Could not read config file. Exiting...
2024-05-28 14:46:47,677 - Could not read config file. Exiting...
2024-05-28 16:49:48,573 - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-3557a1c9303sm12198958f8f.88 - gsmtp')
Traceback (most recent call last):
  File "/Users/yoznacks/Projects/Scholarships/SEGAL/EPOS/EPOS-Providers-DB-Upload/Software/provider_db_upload/fileHandler/fileHandler.py", line 103, in send_email
    server.login(self.from_email,self.from_email_password)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 750, in login
    raise last_exception
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-3557a1c9303sm12198958f8f.88 - gsmtp')2024-05-28 16:51:32,191 - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-359b3675c6csm5113389f8f.71 - gsmtp')
Traceback (most recent call last):
  File "/Users/yoznacks/Projects/Scholarships/SEGAL/EPOS/EPOS-Providers-DB-Upload/Software/provider_db_upload/fileHandler/fileHandler.py", line 102, in send_email
    server.login(self.from_email,self.from_email_password)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 750, in login
    raise last_exception
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-359b3675c6csm5113389f8f.71 - gsmtp')
2024-05-28 16:52:03,068 - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-3557a1c9363sm12141245f8f.72 - gsmtp')
Traceback (most recent call last):
  File "/Users/yoznacks/Projects/Scholarships/SEGAL/EPOS/EPOS-Providers-DB-Upload/Software/provider_db_upload/fileHandler/fileHandler.py", line 102, in send_email
    server.login(self.from_email,self.from_email_password)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 750, in login
    raise last_exception
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-3557a1c9363sm12141245f8f.72 - gsmtp')
